### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by CairoLee** [lucascaro/hexo-deployer-sftp#1]
**NPM Version:** 2.15.11
**NodeJS Version:** v4.8.3

After i install hexo, i run `npm install hexo-deployer-sftp --save` to install hexo-deployer-sftp, but look like it's not working. 

```
ERROR Plugin load failed: hexo-deployer-sftp
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Sean/Documents/Dev/blog/node_modules/hexo-deployer-sftp/node_modules/sftp-sync-deploy/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (/Users/Sean/Documents/Dev/blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /Users/Sean/Documents/Dev/blog/node_modules/hexo-deployer-sftp/index.js:1:81
    at /Users/Sean/Documents/Dev/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/Sean/Documents/Dev/blog/node_modules/bluebird/js/release/promise.js:638:18)
```

**Comment by lucascaro** [comment]
Thanks for the report @CairoLee! This looks like it might be an error with one of the dependencies. Can you try with a newer version of node? (6 should be good)

**Comment by CairoLee** [comment]
@lucascaro Thankyou！After i update nodejs to v6.x.x, this problem is solved
